Web-Terminal/app/bundle/main/__init__.py
from flask import Blueprint


main = Blueprint("main", __name__, template_folder="templates")

Web-Terminal/app/bundle/main/views.py
from .                  import main
from ..command_handler  import handle_request
from ..render           import render


from flask              import current_app, request
from datetime           import datetime
from re                 import compile as re_compile
from platform           import (
    machine   as platform_machine,
    node      as platform_node,
    processor as platform_cpu,
    system    as platform_system,
    version   as platform_version
)


@main.route("/", methods=["GET", "POST"])
def root():
    with current_app.app_context():
        if request.method == "POST" and (handle := handle_request(current_app)):
            return handle
    
    return render("routes/root.html", route="~")


@main.route("/ls", methods=["GET"])
def list_folders():
    return render("information/list_folders.html")


@main.route("/help", methods=["GET"])
def help():
    return render("information/help.html")


@main.route("/whois", methods=["GET"])
def whois():
    return render("information/whois.html")


@main.route("/projects", methods=["GET"])
def projects():
    return render("information/projects.html")


@main.route("/about", methods=["GET", "POST"])
def about():
    with current_app.app_context():
        if request.method == "POST" and (handle := handle_request(current_app)):
            return handle
        
    return render("routes/about.html", route=request.path)


@main.route("/gamehacking", methods=["GET", "POST"])
def gamehacking():
    with current_app.app_context():
        if request.method == "POST" and (handle := handle_request(current_app)):
            return handle
    
    return render("routes/gamehacking.html", route=request.path)


@main.route("/gallery", methods=["GET", "POST"])
def gallery():
    with current_app.app_context():
        if request.method == "POST" and (handle := handle_request(current_app)):
            return handle
    
    return render("routes/gallery.html", route=request.path)


@main.route("/system", methods=["GET", "POST"])
def system():
    with current_app.app_context():
        if request.method == "POST" and (handle := handle_request(current_app)):
            return handle
    
    pattern = re_compile(r'(Mozilla/5.0 \(.*\)) (AppleWebKit/.* \(.*\)) (Chrome/.* Safari/.*)')
    platform, webkit, browser = pattern.match(request.headers.get('User-Agent')).groups() 

    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    os_info = {
        "System":    platform_system(),
        "Node":      platform_node(),
        "Version":   platform_version(),
        "Machine":   platform_machine(),
        "Processor": platform_cpu(),
    }

    return render(
        "routes/system.html", route=request.path,
        ua_platform=platform, ua_webkit=webkit, ua_browser=browser,
        os_info=os_info, current_time=current_time
    )


@main.route('/skills', methods=["GET", "POST"])
@main.route('/skills/<int:id>', methods=["GET", "POST"])
def skills(id: int = None):
    with current_app.app_context():
        if (request.method == "POST") and (handle := handle_request(current_app)):
            return handle
    
    skills = [
        {"name": "Assembly", "description": "Reverse Engineering"},
        {"name": "C++",      "description": "Internal Domain"    },
        {"name": "Python",   "description": "Botnet Producer"    },
        {"name": "Java",     "description": "Stuff Manager"      }
    ]

    if id or id == 0:
        try:
            skill = skills[id]
        except Exception:
            pass

        if skill:
            return render("routes/skill_detail.html", route=request.path, skill=skill)

    return render("routes/skill_list.html", route=request.path, skills=skills)

Web-Terminal/app/bundle/main/templates/information/help.html
<div>
  <hr>
  <pre><span class="text-description">List of available <span class="text-command">commands</span>:</span></pre>
  <pre><span class="text-command">help</span>       -   <span class="text-description">Obviously you already know what that does.</span></pre>
  <pre><span class="text-command">clear</span>      -   <span class="text-description">Clears the terminal screen.</span></pre>
  <pre><span class="text-command">system</span>     -   <span class="text-description">Displays system information and time.</span></pre>
  <pre><span class="text-command">whois</span>      -   <span class="text-description">Who is aASDa213ASD?</span></pre>
  <pre><span class="text-command">projects</span>   -   <span class="text-description">View coding projects.</span></pre>
  <pre><span class="text-command">ls</span>         -   <span class="text-description">Lists available folders.</span></pre>
  <pre><span class="text-command">cd</span>         -   <span class="text-description">Changes current directory.</span></pre>
  <pre><span class="text-command">skills</span>     -   <span class="text-description">Displays skills, you can specify one by id.</span></pre>
  <pre><span class="text-command">login</span>      -   <span class="text-description">Authentication system.</span></pre>
  <pre><span class="text-command">exit</span>       -   <span class="text-description">Destroys current session.</span></pre>
  <pre><span class="text-command">passwd</span>     -   <span class="text-description">Credentials tool-kit.</span></pre>
  <pre><span class="text-command">cookies</span>    -   <span class="text-description">Cookies tool-kit, use set/wipe arguments.</span></pre>
  <pre><span class="text-command">feedback</span>   -   <span class="text-description">Feedbacks, created using PyMySQL + MariaDB.</span></pre>
</div>

Web-Terminal/app/bundle/main/templates/information/list_folders.html
<div>
  <hr>
  <pre><span class="text-description">List of available <span class="text-command">folders</span>:</span></pre>
  <pre><span class="text-command">/</span>              -   <span class="text-description">Root directory.</span></pre>
  <pre><span class="text-command">about</span>          -   <span class="text-description">Explains what this site is about.</span></pre>
  <pre><span class="text-command">gallery</span>        -   <span class="text-description">Showcases of my projects.</span></pre>
  <pre><span class="text-command">gamehacking</span>    -   <span class="text-description">Explains what I'm doing for living.</span></pre>
  <pre><span class="text-command">system</span>         -   <span class="text-description">Contains system information and time.</span></pre>
</div>

Web-Terminal/app/bundle/main/templates/information/projects.html
<div>
  <hr>
  <pre><span class="text-description">List of <span class="text-command">projects</span> I've created/contributed to:</span></pre>
  <pre><span class="text-description">1. </span><span class="text-default"><strong>True-Sight</strong></span><span class="text-command">, League Of Legends team revealer</span>                -  <a class="arrow arrow-right" href="https://github.com/aASDa213ASD/true-sight"><strong>Repository</strong></a></pre>
  <pre><span class="text-description">2. </span><span class="text-default"><strong>Fuck-The-Devil</strong></span><span class="text-command">, External trainer for Devil Daggers</span>         -  <a class="arrow arrow-right" href="https://github.com/aASDa213ASD/fuck-the-devil"><strong>Repository</strong></a></pre>
  <pre><span class="text-description">3. </span><span class="text-default"><strong>Sigscan</strong></span><span class="text-command">, External memory signature scanner</span>                 -  <a class="arrow arrow-right" href="https://github.com/aASDa213ASD/sigscan"><strong>Repository</strong></a></pre>
  <pre><span class="text-description">4. </span><span class="text-default"><strong>ASDWare</strong></span><span class="text-command">, Undetected CS 1.6 External Software</span>               -  <span class="text-special"><strong>Private</strong></span></pre>
  <pre><span class="text-description">5. </span><span class="text-default"><strong>LeagueAI</strong></span><span class="text-command">, OpenCV League Of Legends Bot</span>                     -  <span class="text-special"><strong>Private</strong></span></pre>
  <pre><span class="text-description">6. </span><span class="text-default"><strong>Eclipse</strong></span><span class="text-command">, Internal League Of Legends Script</span>                 -  <span class="text-special"><strong>Private</strong></span></pre>
  <pre><span class="text-description">7. </span><span class="text-default"><strong>Private-Skins</strong></span><span class="text-command">, Internal League Of Legends skin-changer</span>     -  <span class="text-special"><strong>Private</strong></span></pre>
  <pre><span class="text-description">8. </span><span class="text-default"><strong>ARAMBoost</strong></span><span class="text-command">, Auto-seller python bot for black account market</span> -  <span class="text-secondary"><strong>Discontinued</strong></span></pre>
  <pre><span class="text-description">9. </span><span class="text-default"><strong>Echozy.pw</strong></span><span class="text-command">, CS:GO Internal Software</span>                         -  <span class="text-secondary"><strong>Discontinued</strong></span></pre>
  <br>
  <pre><span class="text-description">You can find more here: <a class="arrow arrow-right" href="https://github.com/aASDa213ASD">github.com/aASDa213ASD</a>.</span></pre>
</div>

Web-Terminal/app/bundle/main/templates/information/whois.html
<div>
  <hr>
  <pre><span class="text-description">Hey, I'm <span class="text-important">▒▒▒▒▒▒▒▒▒▒</span></span></pre>
  <pre><span class="text-description">I don't have a certain name to provide. But you can find me at <span class="text-important">number 16</span> of <span class="text-important">group 31.</span></span></pre>
  <pre><span class="text-description">People like me prefer to stay in shadow rather than having a badge.</span></pre>
  <pre><span class="text-description">I'm a software developer at daylight and a reverse engineer at night</span></pre>
  <pre><span class="text-description">who builds <span class="text-important">websites</span>, <span class="text-important">exploits</span>, <span class="text-important">bots</span> and internal/external <span class="text-important">third party tools</span>.</span></pre>
  <pre><span class="text-description">Obviously enough, I prefer <span class="text-important">assembly</span>/<span class="text-important">C++</span> for my so-called hobbie.</span></pre>
  <pre><span class="text-description">Nevertheless, I got to learn <span class="text-important">java</span>, <span class="text-important">python</span>, <span class="text-important">php</span> and couple of <span class="text-important">other languages</span>.</span></pre>
  <pre><span></span></pre>
  <pre><span class="text-description">Feel free to view at my github, type <span class="text-command">'projects'</span> command.</span></pre>
</div>

Web-Terminal/app/bundle/main/templates/routes/about.html
{% extends "base.html" %}

{% block title %}./about{% endblock %}

{% block content %}
  <div id="initial_message">
    <p class="text-description">This is a portfolio of <span class="text-important">student number 16</span> of <span class="text-important">group 31</span></p>
    <p class="text-description">that was made mainly to learn <span class="text-important">Flask</span>.</p>
    <br>
    <p class="text-description">Website provides terminal-like experience</p>
    <p class="text-description">and tells you something about the developer.</p>
    <p class="text-description">Since developer planned to fill this terminal with </p>
    <p class="text-description">more data, we recommend you visiting <span class="text-important">other folders</span>:</p>
    <hr>
    <pre>                                        <span class="text-command">/gamehacking</span>  - <a class="text-default" href="{{url_for('main.gamehacking')}}"><b>Open</b></a></pre>
    <pre>                                        <span class="text-command">/gallery</span>      - <a class="text-default" href="{{url_for('main.gallery')}}"><b>Open</b></a></pre>
    <hr>
  </div>
  {% block output %}{% endblock %}
{% endblock %}

Web-Terminal/app/bundle/main/templates/routes/gallery.html
{% extends "base.html" %}

{% block title %}./gallery{% endblock %}

{% block content %}
  <div id="initial_message">
    <div class="gallery-wrapper">
      <img class="gallery-img" src="{{url_for('static', filename='images/gallery/cs16_1.png')}}" width="800" alt="">
      <img class="gallery-img" src="{{url_for('static', filename='images/gallery/cs16_2.png')}}" alt="">
      <img class="gallery-img" src="{{url_for('static', filename='images/gallery/fl_1.png')}}" alt="">
      <img class="gallery-img" src="{{url_for('static', filename='images/gallery/lol_1.png')}}" alt="">
      <img class="gallery-img" src="{{url_for('static', filename='images/gallery/lol_2.png')}}" alt="">
      <img class="gallery-img" src="{{url_for('static', filename='images/gallery/lol_3.png')}}" alt="">
      <img class="gallery-img" src="{{url_for('static', filename='images/gallery/lol_4.png')}}" alt="">
      <img class="gallery-img" src="{{url_for('static', filename='images/gallery/lol_5.png')}}" alt="">
      <img class="gallery-img" src="{{url_for('static', filename='images/gallery/lol_6.png')}}" alt="">
      <img class="gallery-img" src="{{url_for('static', filename='images/gallery/lol_7.png')}}" alt="">
    </div>
  </div>
  {% block output %}{% endblock %}
{% endblock %}

Web-Terminal/app/bundle/main/templates/routes/gamehacking.html
{% extends "base.html" %}

{% block title %}./gamehacking{% endblock %}

{% block content %}
  <div id="initial_message">
    <p class="text-description">First you will get informed about what game hacking even is:</span></p>
    <p class="text-description">This field is insanely large and has tons of hardships.</span></p>
    <br>
    <p class="text-description">Game hacking can be separated into two main categories:</span></p>
    <p class="text-description">1. <span class="text-important">Cheats</span>.</p>
    <p class="text-description">2. <span class="text-important">Exploits</span>.</p>
    <br>
    <p class="text-description">Cheat represents an action that a player can perform within the game</span></p>
    <p class="text-description">but this action is done programmatically instead.</span></p>
    <br>
    <p class="text-description">Exploit represents the complete break of the rules,</span></p>
    <p class="text-description">an action that normal player can not do.</span></p>
    <hr>
    <p class="text-muted"><i>- Now you know what game-hacking is, but how it's done?</i></p>
    <p class="text-description">The way we hack can be separated as well: <span class="text-important">Internal</span>/<span class="text-important">External</span>.</p>
    <p class="text-description">Difference is huge, on external side you create a program</p>
    <p class="text-description">that runs along with target process and read it's memory.</p>
    <p class="text-description">On the other hand, internal side requires you to inject</p>
    <p class="text-description">a dynamic library inside target's memory space.</p>
    <br>
    <p class="text-description">You will need a help of <span class="text-important">math</span> if you want to build something worthy.</p>
    <p class="text-description">But only math is not enough, you have to understand how target process</p>
    <p class="text-description">is built inside, for that you have to understand <span class="text-important">assembly</span>.</p>
    <p class="text-description">You need to know which function to call, with what arguments.</p>
    <p class="text-description">Otherwise, <span class="text-important">memory will corrupt</span> and process will eventually die.</p>
    <hr>
    <p class="text-muted"><i>- In other words, this world consumed my brain entirely.</i></p>
    <p class="text-description">From now on you can fully understant the complexity of hacking</p>
    <p class="text-description">and I remember days when I thought <span class="text-muted">"C++ is hard"</span></p>
    <p class="text-description">but little I knew that game hacking is even harder.</p>
    <hr>
    <p class="text-muted"><i>- If you've read everything above: you are ready.</i></p>
    <p><span class="text-description">You've been invited to visit route <span class="text-command">'/gallery'</span></span>  - <a class="text-default" href="{{url_for('main.gallery')}}"><b>Open</b></a><p>
  </div>
  {% block output %}{% endblock %}
{% endblock %}

Web-Terminal/app/bundle/main/templates/routes/root.html
{% extends "base.html" %}

{% block title %}./root{% endblock %}

{% block content %}

  <div id="initial_message">
  <pre>  <span class="text-secondary">Everything is</span>   <b> open source </b></pre>
    <strong><pre class="text-important">
         __...--~~~~~-._   _.-~~~~~--...__
       //  mov eax,0x0  `V'   jmp 1293    \\  
      //  lea rdi,[0xe]  |   call 1090     \\  
     //__...--~~~~~~-._  |  _.-~~~~~~--...__\\
    //__.....----~~~~._\ | /_.~~~~----.....__\\
   ====================\\|//===================
                       `---`</pre></strong>
    <pre>  <span class="text-secondary">if you can</span>     <b> read assembly </b>.</pre>
    <br>
    <p class="text-description">Welcome to unix-based web terminal.</p>
    <p class="text-description">For a list of available commands, type <span class="text-command">'help'.</span></p>
  </div>
  {% block output %}{% endblock %}
{% endblock %}

Web-Terminal/app/bundle/main/templates/routes/skill_detail.html
{% extends "base.html" %}

{% block title %}./skills - {{skill.name}}{% endblock %}

{% block content %}
  <div id="initial_message">
    <p><span class="text-description">Skill <span class="text-important">{{skill.name}}</span>:</span></p>
    <p><strong class="text-important">{{ skill["description"]  }}</strong></span></p>
  </div>
  {% block output %}{% endblock %}
{% endblock %}

Web-Terminal/app/bundle/main/templates/routes/skill_list.html
{% extends "base.html" %}

{% block title %}./skills - All Skills{% endblock %}

{% block content %}
  <div id="initial_message">
    <p><span class="text-description">All skills:</span></p>
    <div>
      {% for skill in skills %}
          <p><strong class="text-description">{{ skill.name }}:</strong> <span class="text-important">{{ skill.description }}</span></p>
      {% endfor %}
    </div>
  </div>
  {% block output %}{% endblock %}
{% endblock %}

Web-Terminal/app/bundle/main/templates/routes/system.html
{% extends "base.html" %}

{% block title %}./system{% endblock %}

{% block content %}
  <div id="initial_message">
    <div>
      {% for key, value in os_info.items() %}
          <p><strong class="text-description">{{ key }}:</strong> <span class="text-important">{{ value }}</span></p>
      {% endfor %}
    </div>
    <br>

    <p><span class="text-description">User Agent:</span></p>
    <p><span class="text-important">{{ ua_platform }}</span></p>
    <p><span class="text-important">{{ ua_webkit }}</span></p>
    <p><span class="text-important">{{ ua_browser }}</span></p>
    <br>

    <p><span class="text-description">Time:</span> <span class="text-important">{{ current_time }}</span></p>
  </div>
  {% block output %}{% endblock %}
{% endblock %}